spring.application.name=pruebaMakers

spring.datasource.url=jdbc:mysql://mysql-1dea188f-college-database.k.aivencloud.com:28726/makers?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_y2ymOKGKPdE2pJ7bn9B
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080